baseURL: "/"
languageCode: en-us
title: Pierre Corazo Cesario
themesDir: "../themes"
theme: "PaperMod"

menu:
  main:
    - name: Search
      url: "/search"
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 50
    - identifier: uptime-kuma
      name: Live Service Status
      url: https://status.pierreccesario.com
      weight: 120

params:
  env: "production"
  disableThemeToggle: true
  defaultTheme: dark
  googleAnalyticsID: "G-8XRXNCDV3N"
  ShowCodeCopyButtons: true
  ShowToc: true
  profileMode:
    enabled: true
    title: "Pierre Corazo Cesario"
    subtitle: "Site Reliability Engineer"
    buttons:
      - name: Experience
        url: "/experience"
      - name: Projects
        url: "/projects"
      - name: Blog
        url: "/blog"

  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/pierreccesario/"
    - name: "GitHub"
      url: "https://github.com/PScoriae"
    - name: "StackOverflow"
      url: "https://stackoverflow.com/users/17645610/pscoriae"
    - name: "Email"
      url: "mailto:contact@pierreccesario.com"
    - name: "AppleMusic"
      url: "https://music.apple.com/profile/pierreccesario"
    - name: rss
      url: "/index.xml"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

deployment:
  targets:
    name: S3 pierreccesario.com
    URL: "s3://pierreccesario.com?region=ap-southeast-1"
