baseURL: "/"
languageCode: en-us
title: Pierre Corazo Cesario
themesDir: "../themes"
theme: "PaperMod"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags
      weight: 50
    - identifier: music-reviews
      name: Music Reviews
      url: https://music.pierreccesario.com
      weight: 100

params:
  env: "production"
  googleAnalyticsID: "G-8XRXNCDV3N"
  profileMode:
    enabled: true
    title: "Pierre Corazo Cesario"
    subtitle: "Backend Software and DevOps Engineer"
    buttons:
      - name: Experience
        url: "/experience"
      - name: Projects
        url: "/projects"

  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/pierreccesario/"
    - name: "GitHub"
      url: "https://github.com/PScoriae"
    - name: "StackOverflow"
      url: "https://stackoverflow.com/users/17645610/pscoriae"
    - name: "Email"
      url: "mailto:contact@pierreccesario.com"
    - name: "Discord"
      url: "https://discordapp.com/users/158403963501281280"
    - name: "Spotify"
      url: "https://open.spotify.com/user/pietries?si=810fe97c34fa489b"
    - name: "AppleMusic"
      url: "https://music.apple.com/profile/pierreccesario"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

deployment:
  targets:
    name: S3 pierreccesario.com
    URL: "s3://pierreccesario.com?region=ap-southeast-1"
