baseURL: "/"
languageCode: en-us
title: Pie's Music Vault
themesDir: "../themes"
theme: "PaperMod"

pluralizeListTitles: false # prevent content folders from being pluralised
enableGitInfo: true

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: rating-system
      name: Rating System
      url: /rating-system
      weight: 10
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags
      weight: 80
    - identifier: Archives
      name: Archives
      url: /archives
      weight: 100

params:
  env: "production"
  googleAnalytics: "G-PDTHCGQGHJ"
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  author: ["Pierre Corazo Cesario"]
  ShowPostNavLinks: true
  mainSections:
    - LE-SSERAFIM
    - poppy
    - TWICE

  homeInfoParams:
    Title: The Music Vault
    Content: My thoughts on songs that intrigue me.

  socialIcons:
    - name: "AppleMusic"
      url: "https://music.apple.com/profile/pierreccesario"
    - name: "Discord"
      url: "https://discordapp.com/users/158403963501281280"
    - name: "kofi"
      url: "https://ko-fi.com/pierreccesario"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

deployment:
  targets:
    name: S3 pierreccesario.com
    URL: "s3://music.pierreccesario.com?region=ap-southeast-1"
