pipeline {

    agent any
    
    stages {
        stage("Hugo Build Music Site") {
            steps {
                dir('music') {
                    sh 'sudo /usr/local/bin/hugo'
                }
            }
        }

        stage("Push Music Files to S3 Bucket") {
            steps {
                dir('music') {
                    sh 'hugo deploy'
                }
            }
        }
    }
}