name: music.pierreccesario.com CI

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: [ "music/**" ]

defaults:
  run:
    working-directory: ./music

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # for aws creds
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      
      - name: Build Site
        run: hugo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::714188290514:role/github-manage-s3-music.pierreccesario.com
          aws-region: ap-southeast-1
      
      - name: Deploy to S3
        run: hugo deploy
